name: Cancel
on:
    push:
      branches:
        - selenium-grid
jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: styfle/cancel-workflow-action
        with:
          workflow_id: 5152358125, 5152319783, 5151810668